#!/usr/bin/env tsx
/**
 * Fixture Deck Generator
 * Produces a PPTX with every chart type and layout archetype.
 * Use to verify cross-app compatibility:
 *   1. Run: npx tsx scripts/generate-fixture-deck.ts
 *   2. Open in PowerPoint → verify all charts render
 *   3. Open in Google Slides → verify all charts render
 *   4. Open in Keynote → verify all charts render
 *   5. Check: fonts, colors, alignment, chart labels, legends
 */

import { writeFileSync } from "fs";
import { renderV2PptxArtifact } from "../packages/render-pptx/src/render-v2";

const SAMPLE_CHARTS = [
  {
    id: "chart-hbar",
    chart_type: "bar",
    title: "Market Share by Brand (Horizontal Bar)",
    data: JSON.stringify({
      labels: ["Brand A", "Brand B", "Brand C", "Brand D", "Brand E"],
      datasets: [{ label: "Value Share %", data: [34.2, 22.1, 15.8, 11.3, 7.4] }],
    }),
    x_axis: "Brand",
    y_axis: "Share %",
    series: JSON.stringify([{ name: "Value Share %", values: [34.2, 22.1, 15.8, 11.3, 7.4] }]),
    style: JSON.stringify({ highlightCategories: ["Brand A"] }),
    intent: "rank",
    source_note: "NielsenIQ RMS Italy, MAT Q1 2025",
  },
  {
    id: "chart-vbar",
    chart_type: "bar",
    title: "Revenue by Quarter (Vertical Bar)",
    data: JSON.stringify({
      labels: ["Q1", "Q2", "Q3", "Q4"],
      datasets: [{ label: "Revenue €M", data: [45.2, 52.1, 48.7, 61.3] }],
    }),
    x_axis: "Quarter",
    y_axis: "Revenue €M",
    series: JSON.stringify([{ name: "Revenue €M", values: [45.2, 52.1, 48.7, 61.3] }]),
    style: JSON.stringify({}),
    intent: "comparison",
    source_note: "Company financials FY2025",
  },
  {
    id: "chart-stacked",
    chart_type: "stacked_bar",
    title: "Category Mix by Segment (Stacked)",
    data: JSON.stringify({
      labels: ["North", "South", "Central"],
      datasets: [
        { label: "Dry", data: [30, 25, 35] },
        { label: "Wet", data: [15, 20, 12] },
        { label: "Treats", data: [8, 10, 6] },
      ],
    }),
    x_axis: "Region",
    y_axis: "Value €M",
    series: JSON.stringify([
      { name: "Dry", values: [30, 25, 35] },
      { name: "Wet", values: [15, 20, 12] },
      { name: "Treats", values: [8, 10, 6] },
    ]),
    style: JSON.stringify({}),
    intent: "composition",
    source_note: "NielsenIQ RMS Italy",
  },
  {
    id: "chart-waterfall",
    chart_type: "waterfall",
    title: "Growth Bridge: Value Change Drivers",
    data: JSON.stringify({
      labels: ["2024 Base", "Price", "Volume", "Mix", "New Products", "2025 Total"],
      datasets: [{ label: "€M", data: [100, 12, -5, 3, 8, 118] }],
    }),
    x_axis: "Driver",
    y_axis: "€M",
    series: JSON.stringify([{ name: "€M", values: [100, 12, -5, 3, 8, 118] }]),
    style: JSON.stringify({}),
    intent: "change",
    source_note: "Growth decomposition analysis",
  },
  {
    id: "chart-donut",
    chart_type: "doughnut",
    title: "Portfolio Split by Category",
    data: JSON.stringify({
      labels: ["Cat Dry", "Cat Wet", "Dog Dry", "Dog Wet", "Treats"],
      datasets: [{ label: "Share %", data: [38, 22, 18, 12, 10] }],
    }),
    x_axis: "",
    y_axis: "",
    series: JSON.stringify([{ name: "Share %", values: [38, 22, 18, 12, 10] }]),
    style: JSON.stringify({}),
    intent: "composition",
    source_note: "Portfolio analysis FY2025",
  },
  {
    id: "chart-line",
    chart_type: "line",
    title: "Market Trend: Value Over Time",
    data: JSON.stringify({
      labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
      datasets: [
        { label: "2024", data: [42, 44, 43, 46, 48, 50] },
        { label: "2025", data: [45, 47, 49, 51, 53, 56] },
      ],
    }),
    x_axis: "Month",
    y_axis: "€M",
    series: JSON.stringify([
      { name: "2024", values: [42, 44, 43, 46, 48, 50] },
      { name: "2025", values: [45, 47, 49, 51, 53, 56] },
    ]),
    style: JSON.stringify({}),
    intent: "trend",
    source_note: "Monthly sales tracking",
  },
];

const SAMPLE_SLIDES = [
  {
    id: "slide-cover",
    position: 1,
    layout_id: "cover",
    title: "Fixture Test Deck — Cross-App Compatibility Validation",
    body: "Generated by Basquio fixture generator. Verify all elements render correctly in PowerPoint, Google Slides, and Keynote.",
    kicker: null,
    callout: null,
    evidence_ids: [],
    metrics: null,
    chart_id: null,
    highlight_categories: null,
  },
  {
    id: "slide-exec",
    position: 2,
    layout_id: "exec-summary",
    title: "Executive Summary: Market grew +3.1% to €2.2B driven by premiumization",
    body: "The total market expanded moderately, with value growth outpacing volume. Premium segments drove 68% of incremental value.",
    kicker: "MARKET OVERVIEW",
    callout: { text: "Premium mix shift is structural — invest in value-accretive innovation", tone: "green" },
    evidence_ids: [],
    metrics: [
      { label: "MARKET SIZE", value: "€2.23B", delta: "+3.1%" },
      { label: "VOLUME", value: "1.8B units", delta: "-0.4%" },
      { label: "AVG PRICE", value: "€1.24", delta: "+3.5%" },
      { label: "BRAND SHARE", value: "34.2%", delta: "+1.2pp" },
    ],
    chart_id: null,
    highlight_categories: null,
  },
  {
    id: "slide-hbar",
    position: 3,
    layout_id: "title-chart",
    title: "Brand A leads with 34.2% share, but Brand B is closing the gap at +2.1pp",
    body: null,
    kicker: "COMPETITIVE LANDSCAPE",
    callout: { text: "Brand B's acceleration requires defensive response in Q3", tone: "orange" },
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-hbar",
    highlight_categories: ["Brand A"],
  },
  {
    id: "slide-vbar",
    position: 4,
    layout_id: "chart-split",
    title: "Q4 revenue surge (+26%) signals seasonal sensitivity in the portfolio",
    body: "Revenue peaked at €61.3M in Q4, driven by holiday demand. Q2 was the second strongest quarter. The volatility suggests opportunity for counter-seasonal activation.",
    kicker: "QUARTERLY PERFORMANCE",
    callout: null,
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-vbar",
    highlight_categories: null,
  },
  {
    id: "slide-stacked",
    position: 5,
    layout_id: "title-chart",
    title: "Dry dominates all regions but South skews wet (+20% vs national average)",
    body: null,
    kicker: "REGIONAL MIX",
    callout: { text: "South represents the highest wet potential — align distribution accordingly", tone: "green" },
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-stacked",
    highlight_categories: null,
  },
  {
    id: "slide-waterfall",
    position: 6,
    layout_id: "title-chart",
    title: "Price contributed €12M to growth while volume declined €5M — net premiumization",
    body: null,
    kicker: "GROWTH BRIDGE",
    callout: null,
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-waterfall",
    highlight_categories: null,
  },
  {
    id: "slide-donut",
    position: 7,
    layout_id: "chart-split",
    title: "Cat nutrition is 60% of portfolio but dog represents the faster growth opportunity",
    body: "Cat dry and cat wet together account for 60% of portfolio value. Dog segments are smaller but growing faster, suggesting rebalancing opportunity.",
    kicker: "PORTFOLIO STRUCTURE",
    callout: { text: "Rebalance innovation pipeline: 40% cat, 40% dog, 20% treats", tone: "accent" },
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-donut",
    highlight_categories: null,
  },
  {
    id: "slide-line",
    position: 8,
    layout_id: "title-chart",
    title: "2025 consistently outperforms 2024 — the growth trajectory is accelerating",
    body: null,
    kicker: "TREND ANALYSIS",
    callout: { text: "If trend holds, FY2025 will exceed €300M — plan capacity accordingly", tone: "green" },
    evidence_ids: [],
    metrics: null,
    chart_id: "chart-line",
    highlight_categories: null,
  },
  {
    id: "slide-table",
    position: 9,
    layout_id: "table",
    title: "Top 5 brands by value share with growth and price index",
    body: "Brand A: €76.3M (34.2%, +4.1%, PI 112) | Brand B: €49.3M (22.1%, +6.2%, PI 98) | Brand C: €35.2M (15.8%, +1.3%, PI 104) | Brand D: €25.2M (11.3%, -2.1%, PI 89) | Brand E: €16.5M (7.4%, +0.5%, PI 76)",
    kicker: "BRAND SCORECARD",
    callout: null,
    evidence_ids: [],
    metrics: null,
    chart_id: null,
    highlight_categories: ["Brand A"],
  },
  {
    id: "slide-summary",
    position: 10,
    layout_id: "summary",
    title: "Three priorities to convert market momentum into sustainable share gain",
    body: "1. **Defend dry cat** — protect 22.7% share stronghold through innovation and promotion\n2. **Expand cat wet** — each 1pp share = €7.8M; target 3pp gain in 18 months\n3. **Triage dog** — narrow the portfolio, redeploy resources to winning segments",
    kicker: "STRATEGIC RECOMMENDATIONS",
    callout: { text: "Combined addressable opportunity: €30M+ incremental revenue within 24 months", tone: "green" },
    evidence_ids: [],
    metrics: null,
    chart_id: null,
    highlight_categories: null,
  },
];

async function main() {
  console.log("Generating fixture deck...");

  // Generate both modes
  for (const mode of ["powerpoint-native", "universal-compatible"] as const) {
    console.log(`\n--- ${mode} mode ---`);
    const artifact = await renderV2PptxArtifact({
      deckTitle: "Basquio Fixture Deck",
      slides: SAMPLE_SLIDES as never,
      charts: SAMPLE_CHARTS as never,
      exportMode: mode,
    });

    const outputPath = `fixture-deck-${mode}.pptx`;
    const buf = Buffer.isBuffer(artifact.buffer) ? artifact.buffer : Buffer.from((artifact.buffer as { data: number[] }).data);
    writeFileSync(outputPath, buf);
    console.log(`Written: ${outputPath} (${buf.length} bytes)`);
  }

  console.log("\n\nFixture decks generated. Test plan:");
  console.log("1. Open fixture-deck-powerpoint-native.pptx in PowerPoint");
  console.log("2. Open fixture-deck-universal-compatible.pptx in Google Slides");
  console.log("3. Open fixture-deck-universal-compatible.pptx in Keynote");
  console.log("4. For each: verify all 10 slides, all 6 chart types, all layouts");
  console.log("5. Check: fonts (Arial), colors, alignment, labels, legends");
}

main().catch(console.error);
