#!/usr/bin/env tsx
/**
 * Fixture Deck Generator
 * Produces a PPTX with every chart type and layout archetype.
 * Use to verify cross-app compatibility:
 *   1. Run: npx tsx scripts/generate-fixture-deck.ts
 *   2. Open in PowerPoint → verify all charts render
 *   3. Open in Google Slides → verify all charts render
 *   4. Open in Keynote → verify all charts render
 *   5. Check: fonts, colors, alignment, chart labels, legends
 */

import { writeFileSync } from "fs";
import { renderV2PptxArtifact } from "../packages/render-pptx/src/render-v2";

// Charts use the DB row format: data is an array of objects, series is an array of column names
const SAMPLE_CHARTS = [
  {
    id: "chart-hbar",
    chartType: "bar",
    title: "Market Share by Brand (Horizontal Bar)",
    data: [
      { Brand: "Brand A", "Share %": 34.2 },
      { Brand: "Brand B", "Share %": 22.1 },
      { Brand: "Brand C", "Share %": 15.8 },
      { Brand: "Brand D", "Share %": 11.3 },
      { Brand: "Brand E", "Share %": 7.4 },
    ],
    xAxis: "Brand",
    yAxis: "Share %",
    series: ["Share %"],
    style: { highlightCategories: ["Brand A"] },
    intent: "rank",
    sourceNote: "NielsenIQ RMS Italy, MAT Q1 2025",
  },
  {
    id: "chart-vbar",
    chartType: "bar",
    title: "Revenue by Quarter (Vertical Bar)",
    data: [
      { Quarter: "Q1", "Revenue €M": 45.2 },
      { Quarter: "Q2", "Revenue €M": 52.1 },
      { Quarter: "Q3", "Revenue €M": 48.7 },
      { Quarter: "Q4", "Revenue €M": 61.3 },
    ],
    xAxis: "Quarter",
    yAxis: "Revenue €M",
    series: ["Revenue €M"],
    style: {},
    intent: "comparison",
    sourceNote: "Company financials FY2025",
  },
  {
    id: "chart-stacked",
    chartType: "stacked_bar",
    title: "Category Mix by Segment (Stacked)",
    data: [
      { Region: "North", Dry: 30, Wet: 15, Treats: 8 },
      { Region: "South", Dry: 25, Wet: 20, Treats: 10 },
      { Region: "Central", Dry: 35, Wet: 12, Treats: 6 },
    ],
    xAxis: "Region",
    yAxis: "Value €M",
    series: ["Dry", "Wet", "Treats"],
    style: {},
    intent: "composition",
    sourceNote: "NielsenIQ RMS Italy",
  },
  {
    id: "chart-waterfall",
    chartType: "waterfall",
    title: "Growth Bridge: Value Change Drivers",
    data: [
      { Driver: "2024 Base", "€M": 100 },
      { Driver: "Price", "€M": 12 },
      { Driver: "Volume", "€M": -5 },
      { Driver: "Mix", "€M": 3 },
      { Driver: "New Products", "€M": 8 },
      { Driver: "2025 Total", "€M": 118 },
    ],
    xAxis: "Driver",
    yAxis: "€M",
    series: ["€M"],
    style: {},
    intent: "change",
    sourceNote: "Growth decomposition analysis",
  },
  {
    id: "chart-donut",
    chartType: "doughnut",
    title: "Portfolio Split by Category",
    data: [
      { Category: "Cat Dry", "Share %": 38 },
      { Category: "Cat Wet", "Share %": 22 },
      { Category: "Dog Dry", "Share %": 18 },
      { Category: "Dog Wet", "Share %": 12 },
      { Category: "Treats", "Share %": 10 },
    ],
    xAxis: "Category",
    yAxis: "Share %",
    series: ["Share %"],
    style: {},
    intent: "composition",
    sourceNote: "Portfolio analysis FY2025",
  },
  {
    id: "chart-line",
    chartType: "line",
    title: "Market Trend: Value Over Time",
    data: [
      { Month: "Jan", "2024": 42, "2025": 45 },
      { Month: "Feb", "2024": 44, "2025": 47 },
      { Month: "Mar", "2024": 43, "2025": 49 },
      { Month: "Apr", "2024": 46, "2025": 51 },
      { Month: "May", "2024": 48, "2025": 53 },
      { Month: "Jun", "2024": 50, "2025": 56 },
    ],
    xAxis: "Month",
    yAxis: "€M",
    series: ["2024", "2025"],
    style: {},
    intent: "trend",
    sourceNote: "Monthly sales tracking",
  },
];

const SAMPLE_SLIDES = [
  {
    id: "slide-cover",
    position: 1,
    layoutId: "cover",
    title: "Fixture Test Deck — Cross-App Compatibility Validation",
    body: "Generated by Basquio fixture generator. Verify all elements render correctly in PowerPoint, Google Slides, and Keynote.",
    kicker: null,
    callout: null,
    evidenceIds: [],
    metrics: null,
    chartId: null,
    highlightCategories: null,
  },
  {
    id: "slide-exec",
    position: 2,
    layoutId: "exec-summary",
    title: "Executive Summary: Market grew +3.1% to €2.2B driven by premiumization",
    body: "The total market expanded moderately, with value growth outpacing volume. Premium segments drove 68% of incremental value.",
    kicker: "MARKET OVERVIEW",
    callout: { text: "Premium mix shift is structural — invest in value-accretive innovation", tone: "green" },
    evidenceIds: [],
    metrics: [
      { label: "MARKET SIZE", value: "€2.23B", delta: "+3.1%" },
      { label: "VOLUME", value: "1.8B units", delta: "-0.4%" },
      { label: "AVG PRICE", value: "€1.24", delta: "+3.5%" },
      { label: "BRAND SHARE", value: "34.2%", delta: "+1.2pp" },
    ],
    chartId: null,
    highlightCategories: null,
  },
  {
    id: "slide-hbar",
    position: 3,
    layoutId: "title-chart",
    title: "Brand A leads with 34.2% share, but Brand B is closing the gap at +2.1pp",
    body: null,
    kicker: "COMPETITIVE LANDSCAPE",
    callout: { text: "Brand B's acceleration requires defensive response in Q3", tone: "orange" },
    evidenceIds: [],
    metrics: null,
    chartId: "chart-hbar",
    highlightCategories: ["Brand A"],
  },
  {
    id: "slide-vbar",
    position: 4,
    layoutId: "chart-split",
    title: "Q4 revenue surge (+26%) signals seasonal sensitivity in the portfolio",
    body: "Revenue peaked at €61.3M in Q4, driven by holiday demand. Q2 was the second strongest quarter. The volatility suggests opportunity for counter-seasonal activation.",
    kicker: "QUARTERLY PERFORMANCE",
    callout: null,
    evidenceIds: [],
    metrics: null,
    chartId: "chart-vbar",
    highlightCategories: null,
  },
  {
    id: "slide-stacked",
    position: 5,
    layoutId: "title-chart",
    title: "Dry dominates all regions but South skews wet (+20% vs national average)",
    body: null,
    kicker: "REGIONAL MIX",
    callout: { text: "South represents the highest wet potential — align distribution accordingly", tone: "green" },
    evidenceIds: [],
    metrics: null,
    chartId: "chart-stacked",
    highlightCategories: null,
  },
  {
    id: "slide-waterfall",
    position: 6,
    layoutId: "title-chart",
    title: "Price contributed €12M to growth while volume declined €5M — net premiumization",
    body: null,
    kicker: "GROWTH BRIDGE",
    callout: null,
    evidenceIds: [],
    metrics: null,
    chartId: "chart-waterfall",
    highlightCategories: null,
  },
  {
    id: "slide-donut",
    position: 7,
    layoutId: "chart-split",
    title: "Cat nutrition is 60% of portfolio but dog represents the faster growth opportunity",
    body: "Cat dry and cat wet together account for 60% of portfolio value. Dog segments are smaller but growing faster, suggesting rebalancing opportunity.",
    kicker: "PORTFOLIO STRUCTURE",
    callout: { text: "Rebalance innovation pipeline: 40% cat, 40% dog, 20% treats", tone: "accent" },
    evidenceIds: [],
    metrics: null,
    chartId: "chart-donut",
    highlightCategories: null,
  },
  {
    id: "slide-line",
    position: 8,
    layoutId: "title-chart",
    title: "2025 consistently outperforms 2024 — the growth trajectory is accelerating",
    body: null,
    kicker: "TREND ANALYSIS",
    callout: { text: "If trend holds, FY2025 will exceed €300M — plan capacity accordingly", tone: "green" },
    evidenceIds: [],
    metrics: null,
    chartId: "chart-line",
    highlightCategories: null,
  },
  {
    id: "slide-table",
    position: 9,
    layoutId: "table",
    title: "Top 5 brands by value share with growth and price index",
    body: "Brand A: €76.3M (34.2%, +4.1%, PI 112) | Brand B: €49.3M (22.1%, +6.2%, PI 98) | Brand C: €35.2M (15.8%, +1.3%, PI 104) | Brand D: €25.2M (11.3%, -2.1%, PI 89) | Brand E: €16.5M (7.4%, +0.5%, PI 76)",
    kicker: "BRAND SCORECARD",
    callout: null,
    evidenceIds: [],
    metrics: null,
    chartId: null,
    highlightCategories: ["Brand A"],
  },
  {
    id: "slide-summary",
    position: 10,
    layoutId: "summary",
    title: "Three priorities to convert market momentum into sustainable share gain",
    body: "1. **Defend dry cat** — protect 22.7% share stronghold through innovation and promotion\n2. **Expand cat wet** — each 1pp share = €7.8M; target 3pp gain in 18 months\n3. **Triage dog** — narrow the portfolio, redeploy resources to winning segments",
    kicker: "STRATEGIC RECOMMENDATIONS",
    callout: { text: "Combined addressable opportunity: €30M+ incremental revenue within 24 months", tone: "green" },
    evidenceIds: [],
    metrics: null,
    chartId: null,
    highlightCategories: null,
  },
];

async function main() {
  console.log("Generating fixture deck...");

  // Generate both modes
  for (const mode of ["powerpoint-native", "universal-compatible"] as const) {
    console.log(`\n--- ${mode} mode ---`);
    const artifact = await renderV2PptxArtifact({
      deckTitle: "Basquio Fixture Deck",
      slides: SAMPLE_SLIDES as never,
      charts: SAMPLE_CHARTS as never,
      exportMode: mode,
    });

    const outputPath = `fixture-deck-${mode}.pptx`;
    const buf = Buffer.isBuffer(artifact.buffer) ? artifact.buffer : Buffer.from((artifact.buffer as { data: number[] }).data);
    writeFileSync(outputPath, buf);
    console.log(`Written: ${outputPath} (${buf.length} bytes)`);
  }

  console.log("\n\nFixture decks generated. Test plan:");
  console.log("1. Open fixture-deck-powerpoint-native.pptx in PowerPoint");
  console.log("2. Open fixture-deck-universal-compatible.pptx in Google Slides");
  console.log("3. Open fixture-deck-universal-compatible.pptx in Keynote");
  console.log("4. For each: verify all 10 slides, all 6 chart types, all layouts");
  console.log("5. Check: fonts (Arial), colors, alignment, labels, legends");
}

main().catch(console.error);
